name: "Assignee lottery"
description: "Automatically assign assignee to Pull Requests"
author: "silentsilas"
branding:
  icon: "award"
  color: "orange"
inputs:
  repo-token:
    description: "Github token secret"
    required: true
  config:
    description: "Path to config file"
    default: ".github/assignee-lottery.yml"
runs:
  using: "node16"
  main: "dist/index.js"
