name: Assign random assignee

on:
  pull_request:
    types:
      - opened

jobs:
  assign_random_reviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
